[package]
name = "herodotus_eth_starknet"
version = "0.1.0"

# See more keys and their definitions at https://docs.swmansion.com/scarb/docs/reference/manifest
[dependencies]
starknet = ">=2.1.0-rc0"
cairo_lib = { path = "../cairo_lib" }
